language: python
cache: pip
sudo: false
python:
  - 2.6
  - 2.7
  - 3.5
  - 3.6
install:
  - python setup.py build_ext --inplace
script:
  - nosetests
notifications:
  email:
    on_failure: change
deploy:
  provider: pypi
  on:
    tags: true
  distributions: sdist
  user: pkittenis
  password:
    secure: sKuPyiakp4nUMvYI1V671PrJ/A+E8KzB9Hf8iwmsfhelOMmVKjDhWze1V+2goMsJE2CcnlV5DmvQYdeCVqXEye5m/PauW3A+4WohGbxI0XdYJSQZPdYE/LHCyNdvDrdNt1kKefwkis+VFmpsVPeT89E4xOn0eCestYaz1r0ptdio1Nx8RARATwTKXbuB4OucTvUWtmRlrJtXV/j/eJWGf+mN/UVwRSeVd0qLqGQwpu+jGzKbpnPgctTYw0XuzGZy14LYpv5ecWeg9FyEFizcvtb9I2jAcVDdmRxOM/9VzQGXhRlHmJ9w9XTMmf1tf0lVcF6rgb1+hvbmb4xHlBVPYzIZfDzrYB7kzvHYLTI/pjcDYtU50GSlZjgjWZ+c23RF5Q2jFSsrJKx68hNlbUW0nTf1SPhLSDiyTE5k7X6Cb1l4G/xzT+qSTT8Erwf1PO1osOitwFY7YNT3md6Dzv9tWRoeC8UI84t5997jt6QqjFjWVXh/5l1hUiZJRbYUkvhB3d/ZGS2Fc3P7CKMrtGdau/F7NioLAefzYeB5K80S/SxgOcvN1NPDxBCJ7R0OadIdLNI4DxdAD+GQpzU7QXi0TQyDP1USB1h4gep9fB9sPi7mq61MS57avEQSYetcZuQaZmBoMDSymNwYerIWEf5Kb2Pe8zcD4dFYQpt6Nazy+tU=
